# Generated by Django 5.2 on 2025-08-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('edicao', models.CharField(max_length=100)),
                ('numero_paginas', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('classificacao', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('sinopse', models.TextField()),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
            ],
        ),
    ]
