# Generated by Django 5.2 on 2025-08-06 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0002_leitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('multa_paga', models.BooleanField(default=False)),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.leitor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.livro')),
            ],
        ),
    ]
