# Generated by Django 5.2 on 2025-08-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0004_alter_emprestimo_data_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitor',
            name='celular',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='recebimento_alertas',
            field=models.BooleanField(default=True),
        ),
    ]
