# Generated by Django 5.2 on 2025-08-12 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0005_alter_leitor_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitor',
            name='recebimento_alertas',
            field=models.CharField(choices=[('email', 'Email'), ('celular', 'Celular')], default='email', max_length=10),
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_devolucao_real', models.DateField()),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('multa_paga', models.BooleanField(default=False)),
                ('emprestimo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.emprestimo')),
            ],
        ),
    ]
