# Generated by Django 5.2 on 2025-08-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0006_alter_leitor_recebimento_alertas_devolucao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='multa_paga',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(default='2025-08-22'),
            preserve_default=False,
        ),
    ]
